### PR TITLE
[MvxForms] NuSpec files refactored:

### PR DESCRIPTION
**Pull request by MobiliTips**
. No more services but abstract base class
. Ability to specify views suffix (like View or Page)

### CODE REVIEW

**Comment by MobiliTips** [comment]
It's only about nuspec .pp files modifications.
With that configuration, no more hack on Core project as almost all is done into the abstract base class hosted by the Forms project.
Then, if needed, specific presenter implementation is done into platform child class.
It's more or less the same working implementation than in my NinjaMvxForms discused sample project.
Probably there's more to do from here with nuget packaging etc...

Let me know.
Jeremy

**Comment by asudbury** [comment]
Will take a look - do you have a sample solution that is generated from the new nuget package? 

I was trying to avoid having mvvmcross referenced from the forms project (I can't work out if that is now the case with your proposed solution)

Great work and yours works and my current version doesn't work for windows phone!

**Comment by MobiliTips** [comment]
"do you have a sample solution that is generated from the new nuget package?"
Previously to this work, I created an MvvmCross pulgin implementing all these classes to be able to work with MvvmCross and Xamarin Forms from blank manualy created MvvmCross solution. Installing this plugin from Nuget configure all solution to work with Forms.
The main difference with that plugin is that ViewModels and Views are both located in the Core project. You can see the source of this plugin and a sample here: https://github.com/MobiliTips/MvxPlugins/tree/master/MobiliTips.MvxPlugin.MvxForms
You can try it creating an MvvmCross project and then install the plugin called "MvvmCross - Xamarin Forms plugin" from nuget (look for tag "MvxForms").
As I said, it's quite the same .pp files in that plugin and in that pull except the project split between VewModels and Views.

"I was trying to avoid having mvvmcross referenced from the forms project (I can't work out if that is now the case with your proposed solution)"
Yes it's now the case as on my side I was trying to avoid having Xamarin Forms referenced from de Core project :) With that solution, the Core project only host MvvmCross as it always did and Forms host Xamarin Forms plus MvvmCross for the need of the abstract presenter base class.
But anyway, if you prefer removing mvvmcross from the Forms project, I could probably move the abstract presenter to the Core project and let only the Views folder into the the Forms project.

let me know

**Comment by asudbury** [comment]
I prefer the forms project to be just the UI elements and not viewmodels - I know everyone doesn't agree with this approach.

IMHO it's a better separation of concerns - it means you could keep the core project and not use forms (like I want to for a project that I want to create a WPF project)

What I'd like to do is give people the option to choose.

Let me think about - I don't want it to be what I want!!!

Really appreciate the work.

**Comment by MobiliTips** [comment]
Well, in fact I definitly agree with your vision :) 
Forms should host views, nothing more. And you're right, from here we can choose using Forms project or not as it only host views...

I'll take a look at this structure in the next days.

Keep in touch

**Comment by MobiliTips** [comment]
Ok my last commit should do the trick.
. MvxFormsBaseViewPresenter.cs moved from Forms to Core project and improved
. MvxFormsApp.cs moved from Forms to Core project (this is only for event subscription/messaging purpose)
. IVewService added to Core project defining GetPage method
. ViewService added to Forms project to implement IViewService where Views are located
. Core nuspec file, the return!
. Forms nuspec updated

The key of this version is that the abstract base class call from the Core the viewservice.getpage to build page and the viewservice itself is implemented where the views are, depending of if there's a Forms project or not. As simple as that: 1 file :)

You can see a working sample implementing of this version here: https://github.com/MobiliTips/NinjaMvxForms

I did not update any nuget on nuget.org as you're the owner of it, but maybe we should give a try of these new packages pushing it as pre-release and see what we get :)

**Comment by asudbury** [comment]
Brilliant - give me a couple of days to look at (but from what you have said sounds good).

Unfortunately other projects getting in the way - hopefully will clear them very soon and get on to this.

Thanks Adrian.

**Comment by MobiliTips** [comment]
Ok let’s resume :
* Create an MvvmCross + Xamarin Forms project for Android, iOS and Windows Phone thanks to Ninja and without any plugin.
* Bugs :
    * Android :
        * Stucks on black screen (empty view). I think the problem comes from XF initialization on MainActivity.cs
    * iOS :
        * Stucks on error « Could not find view for MainViewModel » from the AppDelegate startup.Start() ;
    * Windows Phone :
        * Stucks on the clock screen without any error. Here’s the fix we talked about :
            * Into MvxFormsWindowsPhoneViewPresenter, add this.RootFrame.Navigate(new Uri("/MainPage.xaml", UriKind.Relative)); after this.navigationPage = new NavigationPage(page); to load the MainPage when app starts
            * Set MainPage.xaml build action to Page (Ninja set it to None)
        * Now stucks on black screen (empty view). I think the problem comes from XF initialization on MainPage.xaml.cs
    * Also, Dependency Injection from ViewModel constructors doesn’t work when Ninja bind context directly into views. XF doesn’t know how to resolve it when Page is beeing built so we have to bind context after Page construction or maybe tell XF where to find the Mvx.Resolve but don’t know how. Anyway, removing context binding from xaml or just not check the box on Ninja resolves this problem.
* Improvments :
    * Ability to specify Views suffix from the presenter constructor (in fact the ViewService constructor) into the Setup class of each platform
    * Code refactoring into an abstract presenter base class as we can see that most of platform presenters code is quite the same. 

Ok so I decided to look at what is working on FormsPresenters Cheesebaron plugin and what is not (because I found some bugs to) and from here how to merge best of both world (in my opinion of course :) ).
The result is what I shared to you :
* 1 abstract presenter base class into the core to write common presenter code only once
* 1 inherited platform presenter class on each target
* 1 ViewService to create XF Pages from XF Views thanks to ViewModels with implementation located wherever you want (Core or Forms depending of what checkbox user checked)
* All Android, iOS and WinPhone XF initlialization reshaped to fix init bugs
* Thanks to the IViewService/ViewService project split (IViewService belongs to CoreProject and ViewService belongs to FormsProject) you finaly get Core with only MvvmCross references and Forms with only Xamarin Forms references

Result illustrated here https://github.com/MobiliTips/NinjaMvxForms

Well it’s just a proposition :)
I was trying to fix bugs (adding some code refactoring at the same time) as I want to use Ninja in my next blog post but feel free to take/don’t take what you want of this work.

Keep in touch

**Comment by MobiliTips** [comment]
Just commited a new version :D

Well, I had to make a choice today between my abstract centralized presenter base class, hosted on top of the solution, that reduce amont of same code on each Platform (previous commit) and full independence of both Core and Forms project (this commit). Both have their own advantages.

So here is the "independent" commit (back to your original structure more or less as asked :) )!
* IViewModelService and its implementation hosted by CoreProject
* IViewService and its implementation hosted by FormsProject
* Presenters refined and hosted on each platforms with specific code
* XF Initializations debugged & standardized
* Core only refers to MvvmCross
* Forms only refers to Xamarin.Forms
* Core & Forms don't refer to each other anymore
* You can merge Forms with Core with transparancy depending if Forms checkbox was checked

As always you can see the working result with my updated sample https://github.com/MobiliTips/NinjaMvxForms

I think we're pretty good with that commit.
Let me know...

**Comment by asudbury** [comment]
I like the 'independent' commit  :-) 

will pull probably tomorrow and try and get a build out over the weekend.

great work.

**Comment by asudbury** [comment]
ive messed your pull request up!

ive commited my changes before getting your PR and now its saying i cant do the merge pull request.

id hate you not to get the credit for your great work - whats the best way to sort this?

sorry :-(

**Comment by asudbury** [comment]
@MobiliTips im happy to give you admin access on this repo if you like.

**Comment by MobiliTips** [comment]
Never mind :)

I can fork again, apply and pull tomorrow or modify directly with admin right.
Clearly I can do both, just tell me.

**Comment by asudbury** [comment]
how do i do admin rights (bit of a newbie to git!)  - more than happy to make you admin.

**Comment by MobiliTips** [comment]
kind of git newbie to :)
I think this should do the trick https://help.github.com/articles/adding-collaborators-to-a-personal-repository/
I tried to add you on my NinjaMvxForms repository, don't know if it was successful.

**Comment by MobiliTips** [comment]
Anyway, I just applyed your updates to my fork (your last xsd removed commit), then resolved conflict (just 3 lines on MvxFormsWindowsPhoneViewPresenter.cs), merge all and push again.
Now you should be able to merge my pull again on your side.
Tell me

**Comment by asudbury** [comment]
merge down - also made you admin to the repo - give me a few hours and all try and get updates onto nuget (though if the rugby gets interesting it might be tomorrow!)

**Comment by MobiliTips** [comment]
Sure, no problem.
Rugby first!
By the way, as you may have noticed it, I'm french, sorry for my english level.
Anyway, France's out already so I wonder how we'll play. Tv's on :)

**Pull request merged**
